apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: container-image-
spec:
  entrypoint: wf-test
  imagePullSecrets:
  - name: regcred
  serviceAccountName: argo

  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json


  templates:
  - name: wf-test
    dag:
      tasks:
        - name: build-first-image
          templateRef: 
            name: container-creation-template
            template: build-kaniko-image
          arguments:
            parameters:
            - name: dockerfile
              value: "context/dockerfile"
            - name: context
              value: "s3://my-bucket/context.tar.gz"
            - name: image-name
              value: 192.168.1.20:5000/kaniko-test # i.e.  manoskoutoulakis/test
            - name: image-tag
              value: latest
        - name: build-second-image
          templateRef: 
            name: container-creation-template
            template: build-kaniko-image
          arguments:
            parameters:
            - name: dockerfile
              value: "context/dockerfile1"
            - name: context
              value: "s3://my-bucket/context.tar.gz"
            - name: image-name
              value: 192.168.1.20:5000/kaniko-test-2 # i.e. manoskoutoulakis/secondtest
            - name: image-tag
              value: latest

        - name: test-first-image
          dependencies: [build-first-image]
          templateRef: 
            name: container-creation-template
            template: test-image
          arguments:
            parameters:
            - name: image-name
              value: 192.168.1.20:5000/kaniko-test # i.e. manoskoutoulakis/test
            - name: msg
              value:  "Hello from the first image"
        - name: test-second-image
          dependencies: [build-second-image]
          templateRef: 
            name: container-creation-template
            template: test-image
          arguments:
            parameters:
            - name: image-name
              value: 192.168.1.20:5000/kaniko-test-2 # i.e. manoskoutoulakis/secondtest
            - name: msg
              value:  "Hello from the second image"
