apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: container-creation-template
spec:
  templates:
  - name: build-kaniko-image
    inputs:
      parameters:
        - name: dockerfile
        - name: context
        - name: image-name
        - name: image-tag
    container: 
        volumeMounts:
          - name: kaniko-secret
            mountPath: /kaniko/.docker
          # - name: dockerfile-storage
            # /mountPath: /workspace
        image: gcr.io/kaniko-project/executor:debug
        args:
          - --dockerfile={{inputs.parameters.dockerfile}}
          - --context={{inputs.parameters.context}}
          - --destination={{inputs.parameters.image-name}}:{{inputs.parameters.image-tag}}
          - --insecure=true
          - --skip-tls-verify=true
          - --insecure-registry=true
          - --insecure-pull=true
          - --skip-tls-verify-pull=true        
        env:
          - name: AWS_ACCESS_KEY_ID
            value: ufkMitetuXoEwTnQb9yX
          - name: AWS_SECRET_ACCESS_KEY
            value: Cp70fVf4VkzktdSnVR9AZixDGVg5hhMr28NGydON
          - name: AWS_REGION
            value: us-east-1
          - name: S3_ENDPOINT
            value: http://192.168.1.20:9000
          - name: S3_FORCE_PATH_STYLE
            value: "true"
  - name: test-image
    inputs:
      parameters:
        - name: image-name
        - name: msg
    container:
      image: "{{inputs.parameters.image-name}}"
      command: [echo]
      args: ["{{inputs.parameters.msg}}"]
